# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  vmImageType: windows-latest
  vmImageName: Local Agent
  system.debug: 'false'
  containerRegistry: 'Spred container registry'
  imageRepo: 'authorization'  
  dockerfile: '$(Build.SourcesDirectory)/microservices/spred.api.authorazation/source/Authorization'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageType)
      name: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfile)'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: '$(tag)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes/$(imageRepo)'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: k8sauth
    replicaNo: 1
    container-registry: '$(containerRegistry)/$(imageRepo)'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'AKS spred prod'
    pool: 
      vmImage: $(vmImageType)
      name: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          # - task: KubernetesManifest@1
          #   inputs:
          #     action: 'createSecret'
          #     namespace: 'default'
          #     secretType: 'dockerRegistry'
          #     containerRegistry: $(containerRegistry)  ##????????
          #     connectionType: 'kubernetesServiceConnection'
          #     kubernetesServiceConnection: 'AKS spred prod'
          - task: replacetokens@3
            displayName: Replace Tokens
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/manifests/'
              targetFiles: 'deployment.yaml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#'
              tokenSuffix: '#'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: $(Pipeline.Workspace)/manifests/deployment.yaml
              containers: '$(containerRegistry)/$(imageRepo):$(tag)'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'AKS spred prod'              
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: |
                        $(Pipeline.Workspace)/manifests/service.yaml
                        $(Pipeline.Workspace)/manifests/ingress.yaml
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'AKS spred prod'