apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app-name}
  labels:
    app: ${app-name}
    environment: prod
    tier: backend
spec:
  replicas: #{replicaNo}#
  selector:
    matchLabels:
      app: ${app-name}
  template:
    metadata:
      labels:
        app: ${app-name}
        environment: prod
        tier: backend
    spec:
      nodeSelector:
        agentpool: generalp01
        kubernetes.io/os: linux
      containers:
      - name: ${app-name}
        image: #{container-registry}#
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
        - name: KeyVaultConnectionString
          valueFrom:
            secretKeyRef:
              name: app-configuration-cnct-str
              key: appconfiguration
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
      imagePullSecrets:
        - name: acr-secret
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvprovider-user-msi"