apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvprovider-redis
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: #{client-id}#  # Set the objectId of the azurekeyvaultsecretsprovider identity 
    keyvaultName: #{key-vault-name}#      # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: redis-username
          objectType: secret
          objectVersion: ""
        - | 
          objectName: redis-password
          objectType: secret
          objectVersion: ""
    tenantId: #{tenant-id}#               # The tenant ID of the key vault
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: redis-user
      objectName: redis-username
    - key: redis-password
      objectName: redis-password
    secretName: redis-secrets
    type: Opaque
---