apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvprovider-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: #{client-id}#  # Set the objectId of the azurekeyvaultsecretsprovider identity 
    keyvaultName: #{key-vault-name}#      # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: app-configuration-cnct-str
          objectType: secret
          objectVersion: ""
        - |
          objectName: generated-cert-microsoft-entra
          objectType: secret
          objectVersion: ""
        - |
          objectName: oauth2-proxy-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: oauth2-proxy-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: blob-primary-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: blob-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: blob-primary-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: azuremonitor-conectionstring
          objectType: secret
          objectVersion: ""
    tenantId: #{tenant-id}#               # The tenant ID of the key vault
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: appconfiguration
      objectName: app-configuration-cnct-str
    secretName: app-configuration-cnct-str                    
    type: Opaque
  - data:
    - key: tls.key
      objectName: generated-cert-microsoft-entra
    - key: tls.crt
      objectName: generated-cert-microsoft-entra
    secretName: generatedcert
    type: kubernetes.io/tls
  - data:
    - key: oauth2_proxy_client_id
      objectName: oauth2-proxy-client-id
    secretName: client-id
    type: Opaque
  - data:
    - key: oauth2_proxy_client_secret
      objectName: oauth2-proxy-client-secret
    secretName: client-secret
    type: Opaque
  - data:
    - key: blob-primary-connection-string
      objectName: blob-primary-connection-string
    secretName: secrets-store01-inline
    type: Opaque
  - data:
    - key: RabbitMQConnection
      objectName: rabbitmq-connection-string
    secretName: rabbitmq-conn-secret
    type: Opaque
  - data:
    - key: azuremonitor-conectionstring
      objectName: azuremonitor-conectionstring
    secretName: azuremonitor-conectionstring
    type: Opaque
  - data:
    - key: azurestorageaccountname
      objectName: blob-name
    - key: azurestorageaccountkey
      objectName: blob-primary-key
    secretName: azurefile-secret
    type: Opaque
---