apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: managed-csi
  name: eventstore-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  # azureFile:
  #   secretName: azure-secret
  #   sharedName: eventstore-share
  #   readOnly: false
  csi:
    driver: disk.csi.azure.com
    volumeHandle: #{dickConnectionString}#
    volumeAttributes:
      fsType: ext4