apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-service
  labels:
    app: playlist-service
    environment: prod
    tier: backend
spec:
  replicas: #{replicaNo}#
  selector:
    matchLabels:
      app: playlist-service
  template:
    metadata:
      labels:
        app: playlist-service
        environment: prod
        tier: backend
    spec:
      nodeSelector:
        agentpool: generalp01
        kubernetes.io/os: linux
      containers:
      - name: playlist-service
        image: #{container-registry}#
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
        - name: KeyVaultConnectionString
          valueFrom:
            secretKeyRef:
              name: app-configuration-cnct-str
              key: appconfiguration
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        livenessProbe:
          httpGet:
            path: /healtz/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healtz/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
        - name: acr-secret
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvprovider-user-msi"